
server:
  port: 8080

spring:
  cloud:
    gateway:
      # Gateway ?? ??
      default-filters: # ????
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      # MSA ??? ??
      # ID, ???(uri), ??(Predicate), ??? ????.
      routes:
        - id: user-service
          # ???
          uri: http://localhost:8081
          # ??? ?? Header? Parameter?? HTTP ??? ?? ?? ??
          # ??? ?? ?? localhost:8080/user ???? ?? localhost:8081/user? ??? ??.
          predicates:
            - Path=/user/**
          # GatewayFilter ????, Filter??? ????? ?? ??? ??/?? ??
          filters:
            - name: UserFilter
              args:
                baseMessage: UserFilter
                preLogger: true
                postLogger: true
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
          filters:
            - name: ProductFilter
              args:
                baseMessage: ProductFilter
                preLogger: true
                postLogger: true